### ISSUE TITLE
DDP Analyzer not started, no data shown

### ISSUE THREAD

**Issue by JamborJan** [arunoda/meteor-ddp-analyzer#12]
## Environment
- Debian minimalistic
- Meteor installed via `curl https://install.meteor.com/ | sh`
- Node installed via package manager after `curl -sL https://deb.nodesource.com/set... | bash -` details see https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions
## Reproduce the issue
- Clone a simple app e.g. `git clone https://github.com/bulletproof-meteor/bullet-unblock.git`
- Let it run once just to check that it is really working on port 3000 (Updated to meteor to 1.0.2.1 if not yet done)
- IMPORTANT with all the repos for the BulletProof Meteor course I get often `Unexpected mongo exit code 100. Restarting.`. I’m not sure if it is linked to the Meteor update to 1.0.2.1 or the BulletProof example repos. I did not experience this issue before and since I started the course I’m also using the new Meteor version, so I don’t have a clue what causes the issue. A reboot solves the issue for the moment but it occurs soon again.
- install the DDP analyser `npm i -g ddp-analyzer`
- us it like described here: https://bulletproofmeteor.com/basics/subscription-caching/3
- One terminal session as user: `ddp-analyzer-proxy -m 3000`
- Second terminal session as user: `DDP_DEFAULT_CONNECTION_URL=http://localhost:3030 meteor`
## Result
- Nothing shown in the analyzer
- No data is saved (e.g. when using the test task app the tasks disappear)

**Comment by arunoda** [comment]
Hmm.
That's very strange. There are few different reasons for the mongo issue. see here: http://stackoverflow.com/questions/15610385/meteor-unexpected-mongo-exit-code-100

Could you try using some other OS from here and try the same process: https://www.terminal.com/
And you can create the current problem on there and share that terminal VM with me, I'll try to see what's the issue on there.

**Comment by JamborJan** [comment]
I can give you access to the system, it's only a development system anyway. Please send me a message on a secure way and I will let you know the login information.

I didn't find you on keybase so I've send you an invite.

**Comment by JamborJan** [comment]
No need to keep this open any longer.
