### ISSUE TITLE
Can't seem to install ddp analyzer

### ISSUE THREAD

**Issue by galactictourist** [arunoda/meteor-ddp-analyzer#15]
I am on Mac Yosemite and have the latest node. I run the NPM command and get this

npm ERR! tar.unpack untar error /Users/maclee/.npm/ddp-analyzer/0.3.0/package.tgz
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-g" "ddp-analyzer"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /usr/local/lib/node_modules/ddp-analyzer
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/ddp-analyzer'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/ddp-analyzer']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/ddp-analyzer',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/ddp-analyzer',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-g" "ddp-analyzer"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

**Comment by arunoda** [comment]
This is a permission issue.
You can use _sudo_ to install.

**Comment by galactictourist** [comment]
yep, thank you.

**Comment by arunoda** [comment]
Hope we can close this.
