### ISSUE TITLE
DDP Analyzer Causing SocketJS Error?

### ISSUE THREAD

**Issue by dantzlerwolfe** [arunoda/meteor-ddp-analyzer#18]
@arunoda

I tried out DDP Analyzer yesterday while working through one of the bulletproof tutorial packages. Now, whenever I create a new Meteor app I get the following error in the console repeatedly:

GET http://localhost:3030/sockjs/info?cb=02psj6n_mg net::ERR_CONNECTION_REFUSED

with reference to - sockjs-0.3.4.js:854

I'm a bit of a Meteor newb, so any help is appreciated. Not sure this was caused by my use of DDP Analyzer, but the error only started popping up after I ran the analyzer on port 3030.

**Comment by arunoda** [comment]
Open a new terminal and create apps.
This is because of the DEFAULT_DDP_CONNECTON env. variable.

**Comment by dantzlerwolfe** [comment]
@arunoda. Thanks for helping with such a simple problem!
