### ISSUE TITLE
DDP server port forwarding

### ISSUE THREAD

**Issue by danielqiu** [arunoda/meteor-ddp-analyzer#5]
My server is running at home in an intranet. I forward the request (http://www.example.com) at port 80 to my server (192.168.1.20) at port 3000. If I don't use ddp-analyzer, DDP server is also on port 3000, which works as expected.

However, when I use ddp-analyzer, which runs on port 3030. Even though I forward port 3030 and configure the corresponding VirtualHost on Apache2, it doesn't hit the DDP server. All the requests to http://www.example.com:3030 failed. What am I missing here?

My meteor app is running with the following commands:

<pre>
forever stopall
DDP_DEFAULT_CONNECTION_URL=http://www.example.com:3030 MONGO_URL=mongodb://localhost:27017/danielqiu PORT=3000 ROOT_URL= http://www.example.com forever start ~/example.com/web/bundle/main.js
forever list
</pre>

**Comment by arunoda** [comment]
is your meteorapp and the ddp-analyzer runs on the same server.
See:
https://github.com/arunoda/meteor-ddp-analyzer/blob/master/lib/proxy.js#L81

It had localhost as hardcoded.

If you need to run ddp analyzer somewhere else you need to change that too.
Send me a PR with allowing to set meteor host name via an option. Then it
will work.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by danielqiu** [comment]
My meteorapp and ddp-analyzer run on the same server. What should I do?

**Comment by arunoda** [comment]
Then see port 3030 can be accessible from the outside.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by danielqiu** [comment]
I tested on http://www.portcheckers.com/ with my port 3030 and YES it can be accessible from the outside world.

DDP proxy is running and I have the settings on apache:

```
<VirtualHost *:80>
    ServerAdmin <myemail>@gmail.com
    ServerName <mydomain>.com
    ServerAlias www.<mydomain>.com

    ProxyRequests off
    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>
    <Location />
        ProxyPass http://localhost:3000/
        ProxyPassReverse http://localhost:3000/
    </Location>
</VirtualHost>

<VirtualHost *:3030>
    ServerAdmin <myemail>@gmail.com
    ServerName <mydomain>.com
    ServerAlias www.<mydomain>.com
    ProxyRequests off
    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>
    <Location />
        ProxyPass http://localhost:3030/
        ProxyPassReverse http://localhost:3030/
    </Location>
</VirtualHost>
```

However, on the browser, i see that the access to www.mydomain.com:3030/sockjs/info?cb=someid failed with the status "canceled".

**Comment by danielqiu** [comment]
I used tcpdump command on my ubuntu server to listen port 3030, it showed that the request got forwarded to my server at the expected port 3030. But ddp-analyzer couldn't catch the packet. 

In the packet, I could see that hostname was www.mydomain.com:3030, probably ddp-analyzer expected the hostname to be 192.168.1.x:3030 or only localhost:3030.

**Comment by danielqiu** [comment]
OK, problem solved.
After reading through your source code, I found that I need to specify my meteor port number if it is not 3000, otherwise it would violate same-origin policy. After specifying it, it works now. :)

**Comment by arunoda** [comment]
Good to know that.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
