### ISSUE TITLE
My app is also broken with ddp

### ISSUE THREAD

**Issue by gregoribic** [arunoda/meteor-ddp-analyzer#6]
I saw the option for meteor app port. Now debug is working.

**Comment by arunoda** [comment]
Any updates ? Why did you close this issue.

On Monday, June 16, 2014, gregoribic notifications@github.com wrote:

> Closed #6 https://github.com/arunoda/meteor-ddp-analyzer/issues/6.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-ddp-analyzer/issues/6#event-131701905.

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by gregoribic** [comment]
I didn't saw that there is a parameter to ddp-analyzer to configure on 
which port meteor app runs.

Then I used ddp-analyzer-proxy -h

I wanted to delete this Issue, but didnt found the button.

Your app is a life saver !! Without it, meteor is black magic.

Best regards,
Gregor Ibic

---

Gregor Ibic

## gregor.ibic@intelicom.si

Intelicom d.o.o.
http://www.intelicom.si

## tel# +386 5 630 91 58

http://www.intelidoc.biz - SpeedUp Your Business

**Comment by arunoda** [comment]
Okay cool.

Try Kadira too :) https://kadira.io

On Monday, June 16, 2014, gregoribic notifications@github.com wrote:

> I didn't saw that there is a parameter to ddp-analyzer to configure on
> which port meteor app runs.
> 
> Then I used ddp-analyzer-proxy -h
> 
> I wanted to delete this Issue, but didnt found the button.
> 
> Your app is a life saver !! Without it, meteor is black magic.
> 
> Best regards,
> Gregor Ibic
> 
> ---
> 
> Gregor Ibic
> gregor.ibic@intelicom.si
> 
> ## <javascript:_e(%7B%7D,'cvml','gregor.ibic@intelicom.si');>
> 
> Intelicom d.o.o.
> http://www.intelicom.si
> 
> ## tel# +386 5 630 91 58
> 
> http://www.intelidoc.biz - SpeedUp Your Business
> 
> From: Arunoda Susiripala <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> To: arunoda/meteor-ddp-analyzer
> <meteor-ddp-analyzer@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','meteor-ddp-analyzer@noreply.github.com');>>
> Cc: gregoribic <gregor.ibic@intelicom.si
> <javascript:_e(%7B%7D,'cvml','gregor.ibic@intelicom.si');>>
> Date: 16.06.2014 15:51
> Subject: Re: [meteor-ddp-analyzer] My app is also broken with ddp
> (#6)
> 
> Any updates ? Why did you close this issue.
> 
> On Monday, June 16, 2014, gregoribic <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Closed #6 https://github.com/arunoda/meteor-ddp-analyzer/issues/6.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/arunoda/meteor-ddp-analyzer/issues/6#event-131701905
> > .
> 
> ## 
> 
> ---
> 
> Arunoda Susiripala
> I curate Meteor Weekly - Check it out!
> <
> 
> http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly
> 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-ddp-analyzer/issues/6#issuecomment-46180927
> .

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
